### ISSUE TITLE
Reference genome selection

### ISSUE THREAD

**Issue by willhooper** [UMCUGenetics/CHORD#1]
Hi,

I noticed that CHORD doesn't provide an option to specify the reference genome used by mutSigExtractor, causing an error when trying to run on GRCh38-aligned variants. 

Are there plans to add functionality to specify the reference in a future version of CHORD? 

Thanks,
Will

**Comment by luannnguyen** [comment]
Hi Will,

Again, sorry for the late reply.

extractSigsChord() now has the ref.genome argument, which accepts the name of a BSgenome object.

So the code would be:
install("BSgenome.Hsapiens.UCSC.hg38")
library("BSgenome.Hsapiens.UCSC.hg38")
extractSigsChord(..., ref.genome="BSgenome.Hsapiens.UCSC.hg38")

However, if you want to run CHORD with non-standard vcfs/inputs (as described in the [tutorial](http://htmlpreview.github.io/?https://github.com/luannnguyen/CHORD/blob/master/example/run_chord.html)), you will need to specify:

extractSigsSnv(..., ref.genome="BSgenome.Hsapiens.UCSC.hg38")
extractSigsIndel(..., ref.genome="BSgenome.Hsapiens.UCSC.hg38")

Extracting SV contexts does not rely on a reference genome.

I will update the tutorial about this soon.

Luan

**Comment by jaesvi** [comment]
Hi Luan, 
I am running CHORD and at least in my system extractSigsChord does not work if you specify the ref.genome with quotes:
Error in GenomeInfoDb::seqlevelsStyle(ref.genome) : 
  The style does not have a compatible entry for the species supported by
  Seqname. Please see genomeStyles() for supported species/style

Without the quotes it works well. So it should be:
library("BSgenome.Hsapiens.UCSC.hg38")
extractSigsChord(..., ref.genome=BSgenome.Hsapiens.UCSC.hg38)

Just leaving it here in case someone has the same problem in the future.
Best,

Jose
