### ISSUE TITLE
BEDPE SV support

### ISSUE THREAD

**Issue by willhooper** [UMCUGenetics/CHORD#2]
Hi,

Are there any plans for adding support for SV input in BEDPE format? 

Thanks,
Will

**Comment by luannnguyen** [comment]
Hi Will,

Sorry for the very late reply. I didn't have notifications set up for github, so i didn't realize that you posted an issue here.

In any case, i've included a [tutorial](http://htmlpreview.github.io/?https://github.com/luannnguyen/CHORD/blob/master/example/run_chord.html) in the repository which has a section on how to deal with non-standard inputs (section 2.). For now you could use the workflow mentioned there, but i will add BEDPE support and get back to you soon.

Luan
