### ISSUE TITLE
CHORD not working with new version of mutSigExtractor?

### ISSUE THREAD

**Issue by ahwanpandey** [UMCUGenetics/CHORD#3]
Hello,

I recently updated both CHORD and mutSigExtractor to the latest versions (CHORD = 1.07, mutSigExtractor = 1.05). Now, all the SV results are 0 when running generateSignatures with a manta VCF, and with GRIDSS the number don't look right anymore.

If I directly run "variantsFromVcf" of mutSigExtractor the I get weird results too:

MANTA
```
variantsFromVcf(
+   manta_file,
+   mode = "sv",
+   sv.caller = "manta",
+   ref.genome = DEFAULT_GENOME,
+   chrom.group = "all",
+   vcf.filter = NA,
+   verbose = F
+ )
                sv_type sv_len
1       BPI_END=4143135     NA
2    BPI_AF=0.146,0.079     NA
3    BPI_AF=0.128,0.070     NA
4      BPI_END=15389540     NA
5    BPI_AF=0.266,0.160     NA
6      BPI_END=40228937     NA
7      BPI_END=39988786     NA
```

GRIDSS
```
> variantsFromVcf(
+   gridss_file,
+   mode = "sv",
+   sv.caller = "gridss",
+   ref.genome = DEFAULT_GENOME,
+   chrom.group = "all",
+   vcf.filter = NA,
+   verbose = F
+ )
    sv_type    sv_len
1       DUP       495
2       TRA        NA
3       SGL        NA
4       SGL        NA
5       SGL        NA
6       SGL        NA
7       DEL        19
8       SGL        NA
9       SGL        NA
10      DEL        24
11      DEL        32
12      SGL        NA
13      SGL        NA
14      INV 249229486
15      INV 249229357
16      SGL        NA
17      TRA        NA
18      TRA        NA
```

Everything was fine before I updated. Please help!

Thanks.

**Comment by ahwanpandey** [comment]
I can verify that if I install the same older versions of CHORD, things are working like before.

devtools::install_github("UMCUGenetics/CHORD@1.01")
devtools::install_github("UMCUGenetics/mutSigExtractor@1.01")

**Comment by ahwanpandey** [comment]
Just tried version 1.05 for both CHORD and mutSigExtractor, and the SV results are all 0 for manta:

devtools::install_github("UMCUGenetics/CHORD@1.05")
devtools::install_github("UMCUGenetics/mutSigExtractor@1.05")

I am happy to keep using version 1.01; but have there been any major updates that would change the results by much between the new and old versions?

Thanks.

**Comment by luannnguyen** [comment]
Hi,

In theory there should be no change to the results since the underlying CHORD model is the same.

I've updated mutSigExtractor (1.06) / CHORD(1.08) to fix the issue with the Manta vcfs. Could you check if you now get the correct output? 

Luan
