### ISSUE TITLE
Fail to install CHORD due to 'randomForest' version

### ISSUE THREAD

**Issue by heqisun** [UMCUGenetics/CHORD#4]
I followed the installation instruction but got this error:
`Error: (converted from warning) package 'randomForest' was built under R version 3.6.2
Execution halted`

**Comment by luannnguyen** [comment]
Updating your R version to 3.6.2 would likely fix this.
Otherwise, try the solution posted here: https://github.com/r-lib/remotes/issues/403#issuecomment-513891775
