### ISSUE TITLE
Error with extractSigsChord

### ISSUE THREAD

**Issue by benjamin-leibowitz** [UMCUGenetics/CHORD#7]
Hi! Love the paper! I'm getting an error with extractSigsChord()

`Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqinfo’ for signature ‘"factor"’`

Using R 3.6

**Comment by luannnguyen** [comment]
Hi Benjamin,

Probably your chromosome names are being read in as factors instead of characters.
You could add `options(stringsAsFactors=FALSE)` add the start of your script.
Alternatively, when you read in your data, you could do `read.table('path/to/txt', stringsAsFactors=FALSE)`

Luan

**Comment by benjamin-leibowitz** [comment]
THAT WORKED THANK YOU SO MUCH @luannnguyen
